// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class CalendarManager{
		private IntPtr objPtr; // opaque VidyoCalendarManager reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoCalendarManagerConstructNative(IntPtr feedback);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarManagerCreateCalendarInstanceNative(IntPtr calMgr, IntPtr feedback, [MarshalAs(UnmanagedType.LPStr)]String svcId, [MarshalAs(UnmanagedType.LPStr)]String calendarName, [MarshalAs(UnmanagedType.LPStr)]String createToken);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCalendarManagerDeleteCalendarInstanceNative(IntPtr calMgr, IntPtr cal);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCalendarManagerDestructNative(IntPtr calendarMgr);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarManagerGetCalendarTypesNative(IntPtr calendarMgr, IntPtr serviceTypes);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarManagerInitializeNative(IntPtr calendarMgr);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarManagerSetCalendarTypesNative(IntPtr calendarMgr, IntPtr serviceTypes);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarManagerUninitializeNative(IntPtr calendarMgr);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoCalendarManagerGetUserDataNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoCalendarManagerSetUserDataNative(IntPtr obj, IntPtr userData);

		public CalendarManager(CalendarManagerFeedback feedback){
			objPtr = VidyoCalendarManagerConstructNative(feedback.GetObjectPtr());
			VidyoCalendarManagerSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		~CalendarManager(){
			if(objPtr != IntPtr.Zero){
				VidyoCalendarManagerSetUserDataNative(objPtr, IntPtr.Zero);
				VidyoCalendarManagerDestructNative(objPtr);
			}
		}
		public Boolean CreateCalendarInstance(CalendarFeedback feedback, String svcId, String calendarName, String createToken){

			Boolean ret = VidyoCalendarManagerCreateCalendarInstanceNative(objPtr, (feedback != null) ? feedback.GetObjectPtr():IntPtr.Zero, svcId, calendarName, createToken);

			return ret;
		}
		public void DeleteCalendarInstance(Calendar cal){

			VidyoCalendarManagerDeleteCalendarInstanceNative(objPtr, (cal != null) ? cal.GetObjectPtr():IntPtr.Zero);
		}
		public Boolean GetCalendarTypes(List<CalendarManagerDefaultServices> serviceTypes){

			IntPtr nServiceTypes = IntPtr.Zero;

			Boolean ret = VidyoCalendarManagerGetCalendarTypesNative(objPtr, nServiceTypes);

			return ret;
		}
		public Boolean Initialize(){

			Boolean ret = VidyoCalendarManagerInitializeNative(objPtr);

			return ret;
		}
		public Boolean SetCalendarTypes(List<CalendarManagerDefaultServices> serviceTypes){

			IntPtr nServiceTypes = IntPtr.Zero;

			Boolean ret = VidyoCalendarManagerSetCalendarTypesNative(objPtr, nServiceTypes);

			return ret;
		}
		public Boolean Uninitialize(){

			Boolean ret = VidyoCalendarManagerUninitializeNative(objPtr);

			return ret;
		}
	};
}
