// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class EndpointPKG{

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoClientGetBuildTagNative();

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoClientGetVersionNative();

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoClientGetVersionWithoutBuildNumberNative();

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoClientInitializeNative();

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoClientSetExperimentalOptionsNative([MarshalAs(UnmanagedType.LPStr)]String options);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoClientUninitializeNative();

		public static String GetBuildTag(){

			IntPtr ret = VidyoClientGetBuildTagNative();

			return Marshal.PtrToStringAnsi(ret);
		}
		public static String GetVersion(){

			IntPtr ret = VidyoClientGetVersionNative();

			return Marshal.PtrToStringAnsi(ret);
		}
		public static String GetVersionWithoutBuildNumber(){

			IntPtr ret = VidyoClientGetVersionWithoutBuildNumberNative();

			return Marshal.PtrToStringAnsi(ret);
		}
		public static Boolean Initialize(){

			Boolean ret = VidyoClientInitializeNative();

			return ret;
		}
		public static Boolean SetExperimentalOptions(String options){

			Boolean ret = VidyoClientSetExperimentalOptionsNative(options);

			return ret;
		}
		public static void Uninitialize(){

			VidyoClientUninitializeNative();
		}
#if __ANDROID__
		internal static IntPtr javaClassHandle;
		internal static IntPtr javaClassRef;
		static IntPtr javaMethodRef;
		public static void SetApplicationUIContext(Android.App.Activity context)
		{
			javaClassRef = Android.Runtime.JNIEnv.FindClass("com/vidyo/VidyoClient/Connector/Connector", ref javaClassHandle);
			javaMethodRef = Android.Runtime.JNIEnv.GetStaticMethodID(javaClassRef, "SetApplicationUIContext", "(Landroid/app/Activity;)V");
			Android.Runtime.JNIEnv.CallStaticVoidMethod(javaClassRef, javaMethodRef, new Android.Runtime.JValue(context));
		}
#endif
	};
}
