// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LocalRendererStreamStats{
		private IntPtr objPtr; // opaque VidyoLocalRendererStreamStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStreamStatsGetbufferDroppedNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStreamStatsGetbufferSizeNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStreamStatsGetheightNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStreamStatsGetidNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStreamStatsGetnameNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStreamStatsGetwidthNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoLocalRendererStreamStatsGetUserDataNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoLocalRendererStreamStatsSetUserDataNative(IntPtr obj, IntPtr userData);

		public uint bufferDropped;
		public uint bufferSize;
		public ulong height;
		public String id;
		public String name;
		public ulong width;
		public LocalRendererStreamStats(IntPtr obj){
			objPtr = obj;

			bufferDropped = VidyoLocalRendererStreamStatsGetbufferDroppedNative(objPtr);
			bufferSize = VidyoLocalRendererStreamStatsGetbufferSizeNative(objPtr);
			height = VidyoLocalRendererStreamStatsGetheightNative(objPtr);
			id = Marshal.PtrToStringAnsi(VidyoLocalRendererStreamStatsGetidNative(objPtr));
			name = Marshal.PtrToStringAnsi(VidyoLocalRendererStreamStatsGetnameNative(objPtr));
			width = VidyoLocalRendererStreamStatsGetwidthNative(objPtr);
		}
	};
}
