// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LogRecord{
		private IntPtr objPtr; // opaque VidyoLogRecord reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLogRecordGetcategoryNameNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLogRecordGeteventTimeNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogRecordGetfileNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogRecordGetfunctionNameNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern LogLevel VidyoLogRecordGetlevelNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern int VidyoLogRecordGetlineNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogRecordGetmessageNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogRecordGetnameNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogRecordGetthreadNameNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoLogRecordGetUserDataNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoLogRecordSetUserDataNative(IntPtr obj, IntPtr userData);

		public enum LogLevel{
			LoglevelFATAL,
			LoglevelERROR,
			LoglevelWARNING,
			LoglevelINFO,
			LoglevelDEBUG,
			LoglevelSENT,
			LoglevelRECEIVED,
			LoglevelENTER,
			LoglevelLEAVE,
			LoglevelINVALID
		}
		public ulong categoryName;
		public ulong eventTime;
		public String file;
		public String functionName;
		public LogLevel level;
		public int line;
		public String message;
		public String name;
		public String threadName;
		public LogRecord(IntPtr obj){
			objPtr = obj;

			categoryName = VidyoLogRecordGetcategoryNameNative(objPtr);
			eventTime = VidyoLogRecordGeteventTimeNative(objPtr);
			file = Marshal.PtrToStringAnsi(VidyoLogRecordGetfileNative(objPtr));
			functionName = Marshal.PtrToStringAnsi(VidyoLogRecordGetfunctionNameNative(objPtr));
			level = VidyoLogRecordGetlevelNative(objPtr);
			line = VidyoLogRecordGetlineNative(objPtr);
			message = Marshal.PtrToStringAnsi(VidyoLogRecordGetmessageNative(objPtr));
			name = Marshal.PtrToStringAnsi(VidyoLogRecordGetnameNative(objPtr));
			threadName = Marshal.PtrToStringAnsi(VidyoLogRecordGetthreadNameNative(objPtr));
		}
	};
}
