// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class User{
		private IntPtr objPtr; // opaque VidyoUser reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserAddRosterContactNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserAdvancedSearchRoomsNative(IntPtr u, IntPtr fieldSet, IntPtr fieldRelations, IntPtr fieldValues, [MarshalAs(UnmanagedType.LPStr)]String searchToken, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserAdvancedSearchUsersNative(IntPtr u, IntPtr fieldSet, IntPtr fieldValues, [MarshalAs(UnmanagedType.LPStr)]String searchToken, uint index, uint pageSize, OnUserSearchResults onUserSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserAllowSubscriberNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserBlockSubscriberNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserConstructNative(IntPtr endpoint);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserConstructCopyNative(IntPtr other);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserCreateCallNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId, [MarshalAs(UnmanagedType.LPStr)]String createToken, OnCallCreated onCallCreated);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserCreateRoomFromIdNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String id, [MarshalAs(UnmanagedType.LPStr)]String createToken, OnRoomCreated onRoomCreated);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserCreateRoomWithIdNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String id, [MarshalAs(UnmanagedType.LPStr)]String createToken, OnRoomCreated onRoomCreated);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserCreateTopicRoomNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String name, [MarshalAs(UnmanagedType.LPStr)]String description, [MarshalAs(UnmanagedType.LPStr)]String createToken, OnRoomCreated onRoomCreated);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoUserDestructNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetContactNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId, OnGetContactResult onGetContactResult);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetConversationRoomNative(IntPtr u, IntPtr userIds, [MarshalAs(UnmanagedType.LPStr)]String createToken, OnRoomCreated onRoomCreated);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetCurrentRosterNative(IntPtr u, IntPtr roster);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserGetEndpointNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetFavoriteRoomsNative(IntPtr u, uint index, uint pageSize, OnFavoriteRoomResults onFavoriteRoomResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserGetIdNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetRecentRoomsNative(IntPtr u, uint index, uint pageSize, OnRecentRoomResults onRecentRoomResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserGetStatsNative(IntPtr r, IntPtr stats);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLoginNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String username, [MarshalAs(UnmanagedType.LPStr)]String password, [MarshalAs(UnmanagedType.LPStr)]String host, uint port, [MarshalAs(UnmanagedType.LPStr)]String serviceType, OnLoginComplete onLoginComplete, OnLoggedOut onLoggedOut, OnConnectionStatusChanged onConnectionStatusChanged, OnTokenReceived onTokenReceived, OnWebProxyCredentialsRequest onWebProxyCredentialsRequest);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLoginAsGuestNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String displayName, [MarshalAs(UnmanagedType.LPStr)]String host, uint port, [MarshalAs(UnmanagedType.LPStr)]String serviceType, OnLoginComplete onLoginComplete, OnLoggedOut onLoggedOut, OnConnectionStatusChanged onConnectionStatusChanged, OnTokenReceived onTokenReceived, OnWebProxyCredentialsRequest onWebProxyCredentialsRequest);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLoginWithAccessTokenNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String accessToken, [MarshalAs(UnmanagedType.LPStr)]String host, uint port, [MarshalAs(UnmanagedType.LPStr)]String serviceType, OnLoginComplete onLoginComplete, OnLoggedOut onLoggedOut, OnConnectionStatusChanged onConnectionStatusChanged, OnTokenReceived onTokenReceived, OnWebProxyCredentialsRequest onWebProxyCredentialsRequest);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLoginWithRefreshTokenNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String refreshToken, [MarshalAs(UnmanagedType.LPStr)]String host, uint port, [MarshalAs(UnmanagedType.LPStr)]String serviceType, OnLoginComplete onLoginComplete, OnLoggedOut onLoggedOut, OnConnectionStatusChanged onConnectionStatusChanged, OnTokenReceived onTokenReceived, OnWebProxyCredentialsRequest onWebProxyCredentialsRequest);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLoginWithTenantTokenNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String provisionToken, [MarshalAs(UnmanagedType.LPStr)]String host, uint port, [MarshalAs(UnmanagedType.LPStr)]String serviceType, OnLoginComplete onLoginComplete, OnLoggedOut onLoggedOut, OnConnectionStatusChanged onConnectionStatusChanged, OnTokenReceived onTokenReceived, OnWebProxyCredentialsRequest onWebProxyCredentialsRequest);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserLogoutNative(IntPtr user);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserRegisterCallEventListenerNative(IntPtr u, OnCallCreatedByInvite onCallCreatedByInvite);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserRegisterContactEventListenerNative(IntPtr u, OnUpdateSelf onUpdateSelf, OnUpdateRosterContact onUpdateRosterContact, OnRemoveRosterContact onRemoveRosterContact);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserRegisterLicenseEventListenerNative(IntPtr u, OnLicenseReceived onLicenseReceived, OnGetLicenseKey onGetLicenseKey);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserRegisterRoomEventListenerNative(IntPtr u, OnRoomCreatedByInvite onRoomCreatedByInvite);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserRemoveRosterContactNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String userId);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchConversationRoomsNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchRoomsNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchRoomsWithNameNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchRoomsWithOwnerNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchRoomsWithSubjectNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchTopicRoomsNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnRoomSearchResults onRoomSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserSearchUsersNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String searchText, uint index, uint pageSize, OnUserSearchResults onUserSearchResults);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoUserSetCANative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String ca, [MarshalAs(UnmanagedType.LPStr)]String caFilePath, [MarshalAs(UnmanagedType.LPStr)]String caDir);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoUserSetDisplayNameNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String displayName);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoUserSetWebProxyAddressCredentialsNative(IntPtr u, [MarshalAs(UnmanagedType.LPStr)]String proxyAddress, [MarshalAs(UnmanagedType.LPStr)]String username, [MarshalAs(UnmanagedType.LPStr)]String password);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserUnregisterCallEventListenerNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserUnregisterContactEventListenerNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserUnregisterLicenseEventListenerNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserUnregisterRoomEventListenerNative(IntPtr u);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoUserUpdatePresenceNative(IntPtr u, [MarshalAs(UnmanagedType.I4)]Contact.ContactPresenceState state, [MarshalAs(UnmanagedType.LPStr)]String status);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoUserGetUserDataNative(IntPtr obj);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoUserSetUserDataNative(IntPtr obj, IntPtr userData);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnCallCreated(IntPtr u, IntPtr call, UserCallCreateResult result, IntPtr createToken);
		private static OnCallCreated _mOnCallCreated;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnCallCreatedByInvite(IntPtr u, IntPtr call, IntPtr inviter);
		private static OnCallCreatedByInvite _mOnCallCreatedByInvite;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnConnectionStatusChanged(IntPtr u, UserConnectionStatusChangedReason reason);
		private static OnConnectionStatusChanged _mOnConnectionStatusChanged;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnFavoriteRoomResults(IntPtr u, UserSearchResult searchResult, IntPtr roomInfo);
		private static OnFavoriteRoomResults _mOnFavoriteRoomResults;
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnFavoriteRoomResultsGetroomInfoArrayNative(IntPtr obj, ref int size);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnFavoriteRoomResultsFreeroomInfoArrayNative(IntPtr obj, int size);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnGetContactResult(IntPtr u, IntPtr contact, UserGetContactResult result);
		private static OnGetContactResult _mOnGetContactResult;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnGetLicenseKey(IntPtr u, IntPtr licenseKey);
		private static OnGetLicenseKey _mOnGetLicenseKey;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnLicenseReceived(IntPtr u, IntPtr licenseKey);
		private static OnLicenseReceived _mOnLicenseReceived;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnLoggedOut(IntPtr u, UserLogoutReason reason);
		private static OnLoggedOut _mOnLoggedOut;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnLoginComplete(IntPtr u, UserLoginResult result, Boolean secure);
		private static OnLoginComplete _mOnLoginComplete;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRecentRoomResults(IntPtr u, UserSearchResult searchResult, IntPtr roomInfo);
		private static OnRecentRoomResults _mOnRecentRoomResults;
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnRecentRoomResultsGetroomInfoArrayNative(IntPtr obj, ref int size);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnRecentRoomResultsFreeroomInfoArrayNative(IntPtr obj, int size);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRemoveRosterContact(IntPtr u, IntPtr uri);
		private static OnRemoveRosterContact _mOnRemoveRosterContact;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRoomCreated(IntPtr u, IntPtr room, UserRoomCreateResult result, IntPtr createToken);
		private static OnRoomCreated _mOnRoomCreated;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRoomCreatedByInvite(IntPtr u, IntPtr room, IntPtr inviter, IntPtr message);
		private static OnRoomCreatedByInvite _mOnRoomCreatedByInvite;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRoomSearchResults(IntPtr u, IntPtr searchText, UserSearchResult searchResult, IntPtr roomInfo, ulong numRecords);
		private static OnRoomSearchResults _mOnRoomSearchResults;
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnRoomSearchResultsGetroomInfoArrayNative(IntPtr obj, ref int size);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnRoomSearchResultsFreeroomInfoArrayNative(IntPtr obj, int size);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnTokenReceived(IntPtr u, IntPtr token, UserTokenType tokenType);
		private static OnTokenReceived _mOnTokenReceived;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnUpdateRosterContact(IntPtr u, IntPtr contact);
		private static OnUpdateRosterContact _mOnUpdateRosterContact;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnUpdateSelf(IntPtr u, IntPtr contact);
		private static OnUpdateSelf _mOnUpdateSelf;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnUserSearchResults(IntPtr u, IntPtr searchText, UserSearchResult searchResult, IntPtr contacts, ulong numRecords);
		private static OnUserSearchResults _mOnUserSearchResults;
		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnUserSearchResultsGetcontactsArrayNative(IntPtr obj, ref int size);

		[DllImport("libVidyoClient", CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoUserOnUserSearchResultsFreecontactsArrayNative(IntPtr obj, int size);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnWebProxyCredentialsRequest(IntPtr u);
		private static OnWebProxyCredentialsRequest _mOnWebProxyCredentialsRequest;
		public enum RoomSearchField{
			RoomsearchfieldOwner,
			RoomsearchfieldAdmin,
			RoomsearchfieldModerator,
			RoomsearchfieldMember,
			RoomsearchfieldUser,
			RoomsearchfieldName,
			RoomsearchfieldSubject,
			RoomsearchfieldType,
			RoomsearchfieldPublic,
			RoomsearchfieldNonMembers
		}
		public enum RoomSearchFieldRelation{
			RoomsearchfieldrelationAND,
			RoomsearchfieldrelationOR
		}
		public enum UserCallCreateResult{
			UsercallcreateresultOK,
			UsercallcreateresultNoResponse,
			UsercallcreateresultNotAllowed,
			UsercallcreateresultMiscLocalError,
			UsercallcreateresultMiscRemoteError
		}
		public enum UserConnectionStatusChangedReason{
			UserconnectionstatuschangedreasonOK,
			UserconnectionstatuschangedreasonLostContactWithServer,
			UserconnectionstatuschangedreasonNoCommunicationWithServer,
			UserconnectionstatuschangedreasonNoValidNetworkInterfaces,
			UserconnectionstatuschangedreasonNetworkInterfaceChanged,
			UserconnectionstatuschangedreasonMiscNetworkError,
			UserconnectionstatuschangedreasonConnectionError
		}
		public enum UserGetContactResult{
			UsergetcontactresultOK,
			UsergetcontactresultNoResponse,
			UsergetcontactresultUnauthorized,
			UsergetcontactresultMiscLocalError,
			UsergetcontactresultMiscRemoteError
		}
		public enum UserLoginResult{
			UserloginresultOK,
			UserloginresultConnectionFailed,
			UserloginresultConnectionLost,
			UserloginresultConnectionTimeout,
			UserloginresultNoResponse,
			UserloginresultTerminated,
			UserloginresultInvalidUser,
			UserloginresultInvalidPassword,
			UserloginresultMiscAuthError,
			UserloginresultCancelled,
			UserloginresultMiscError,
			UserloginresultWebProxyAuthenticationRequired
		}
		public enum UserLogoutReason{
			UserlogoutreasonLoggedOut,
			UserlogoutreasonConnectionLost,
			UserlogoutreasonConnectionTimeout,
			UserlogoutreasonNoResponse,
			UserlogoutreasonTerminated,
			UserlogoutreasonMiscError
		}
		public enum UserRoomCreateResult{
			UserroomcreateresultOK,
			UserroomcreateresultNoResponse,
			UserroomcreateresultNotFound,
			UserroomcreateresultUnauthorized,
			UserroomcreateresultMiscLocalError,
			UserroomcreateresultMiscRemoteError,
			UserroomcreateresultDuplicateName
		}
		public enum UserSearchField{
			UsersearchfieldUID,
			UsersearchfieldEMAIL,
			UsersearchfieldNAME,
			UsersearchfieldTELNO
		}
		public enum UserSearchResult{
			UsersearchresultOK,
			UsersearchresultNoRecords,
			UsersearchresultNoResponse,
			UsersearchresultMiscLocalError,
			UsersearchresultMiscRemoteError
		}
		public enum UserState{
			UserstateIdle,
			UserstateLoggingIn,
			UserstateLoggedIn,
			UserstateReconnecting
		}
		public enum UserTokenType{
			UsertokentypeRefreshToken,
			UsertokentypeAccessToken
		}
		public interface IAdvancedSearchRooms{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface IAdvancedSearchUsers{

			void OnUserSearchResults(String searchText, UserSearchResult searchResult, List<ContactInfo> contacts, ulong numRecords);
		}
		public interface ICreateCall{

			void OnCallCreated(Call call, UserCallCreateResult result, String createToken);
		}
		public interface ICreateRoomFromId{

			void OnRoomCreated(Room room, UserRoomCreateResult result, String createToken);
		}
		public interface ICreateRoomWithId{

			void OnRoomCreated(Room room, UserRoomCreateResult result, String createToken);
		}
		public interface ICreateTopicRoom{

			void OnRoomCreated(Room room, UserRoomCreateResult result, String createToken);
		}
		public interface IGetContact{

			void OnGetContactResult(Contact contact, UserGetContactResult result);
		}
		public interface IGetConversationRoom{

			void OnRoomCreated(Room room, UserRoomCreateResult result, String createToken);
		}
		public interface IGetFavoriteRooms{

			void OnFavoriteRoomResults(UserSearchResult searchResult, List<RoomInfo> roomInfo);
		}
		public interface IGetRecentRooms{

			void OnRecentRoomResults(UserSearchResult searchResult, List<RoomInfo> roomInfo);
		}
		public interface ILogin{

			void OnLoginComplete(UserLoginResult result, Boolean secure);
			void OnLoggedOut(UserLogoutReason reason);
			void OnConnectionStatusChanged(UserConnectionStatusChangedReason reason);
			void OnTokenReceived(String token, UserTokenType tokenType);
			void OnWebProxyCredentialsRequest();
		}
		public interface ILoginAsGuest{

			void OnLoginComplete(UserLoginResult result, Boolean secure);
			void OnLoggedOut(UserLogoutReason reason);
			void OnConnectionStatusChanged(UserConnectionStatusChangedReason reason);
			void OnTokenReceived(String token, UserTokenType tokenType);
			void OnWebProxyCredentialsRequest();
		}
		public interface ILoginWithAccessToken{

			void OnLoginComplete(UserLoginResult result, Boolean secure);
			void OnLoggedOut(UserLogoutReason reason);
			void OnConnectionStatusChanged(UserConnectionStatusChangedReason reason);
			void OnTokenReceived(String token, UserTokenType tokenType);
			void OnWebProxyCredentialsRequest();
		}
		public interface ILoginWithRefreshToken{

			void OnLoginComplete(UserLoginResult result, Boolean secure);
			void OnLoggedOut(UserLogoutReason reason);
			void OnConnectionStatusChanged(UserConnectionStatusChangedReason reason);
			void OnTokenReceived(String token, UserTokenType tokenType);
			void OnWebProxyCredentialsRequest();
		}
		public interface ILoginWithTenantToken{

			void OnLoginComplete(UserLoginResult result, Boolean secure);
			void OnLoggedOut(UserLogoutReason reason);
			void OnConnectionStatusChanged(UserConnectionStatusChangedReason reason);
			void OnTokenReceived(String token, UserTokenType tokenType);
			void OnWebProxyCredentialsRequest();
		}
		public interface IRegisterCallEventListener{

			void OnCallCreatedByInvite(Call call, Contact inviter);
		}
		public interface IRegisterContactEventListener{

			void OnUpdateSelf(Contact contact);
			void OnUpdateRosterContact(Contact contact);
			void OnRemoveRosterContact(String uri);
		}
		public interface IRegisterLicenseEventListener{

			void OnLicenseReceived(String licenseKey);
			void OnGetLicenseKey(String licenseKey);
		}
		public interface IRegisterRoomEventListener{

			void OnRoomCreatedByInvite(Room room, Contact inviter, String message);
		}
		public interface ISearchConversationRooms{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchRooms{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchRoomsWithName{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchRoomsWithOwner{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchRoomsWithSubject{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchTopicRooms{

			void OnRoomSearchResults(String searchText, UserSearchResult searchResult, List<RoomInfo> roomInfo, ulong numRecords);
		}
		public interface ISearchUsers{

			void OnUserSearchResults(String searchText, UserSearchResult searchResult, List<ContactInfo> contacts, ulong numRecords);
		}
		private static IAdvancedSearchRooms _mIAdvancedSearchRooms;
		private static IAdvancedSearchUsers _mIAdvancedSearchUsers;
		private static ICreateCall _mICreateCall;
		private static ICreateRoomFromId _mICreateRoomFromId;
		private static ICreateRoomWithId _mICreateRoomWithId;
		private static ICreateTopicRoom _mICreateTopicRoom;
		private static IGetContact _mIGetContact;
		private static IGetConversationRoom _mIGetConversationRoom;
		private static IGetFavoriteRooms _mIGetFavoriteRooms;
		private static IGetRecentRooms _mIGetRecentRooms;
		private static ILogin _mILogin;
		private static ILoginAsGuest _mILoginAsGuest;
		private static ILoginWithAccessToken _mILoginWithAccessToken;
		private static ILoginWithRefreshToken _mILoginWithRefreshToken;
		private static ILoginWithTenantToken _mILoginWithTenantToken;
		private static IRegisterCallEventListener _mIRegisterCallEventListener;
		private static IRegisterContactEventListener _mIRegisterContactEventListener;
		private static IRegisterLicenseEventListener _mIRegisterLicenseEventListener;
		private static IRegisterRoomEventListener _mIRegisterRoomEventListener;
		private static ISearchConversationRooms _mISearchConversationRooms;
		private static ISearchRooms _mISearchRooms;
		private static ISearchRoomsWithName _mISearchRoomsWithName;
		private static ISearchRoomsWithOwner _mISearchRoomsWithOwner;
		private static ISearchRoomsWithSubject _mISearchRoomsWithSubject;
		private static ISearchTopicRooms _mISearchTopicRooms;
		private static ISearchUsers _mISearchUsers;
		public User(Endpoint endpoint){
			objPtr = VidyoUserConstructNative(endpoint.GetObjectPtr());
			VidyoUserSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		public User(IntPtr other){
			objPtr = VidyoUserConstructCopyNative(other);
			VidyoUserSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		~User(){
			if(objPtr != IntPtr.Zero){
				VidyoUserSetUserDataNative(objPtr, IntPtr.Zero);
				VidyoUserDestructNative(objPtr);
			}
		}
		public Boolean AddRosterContact(String userId){

			Boolean ret = VidyoUserAddRosterContactNative(objPtr, userId);

			return ret;
		}
		public Boolean AdvancedSearchRooms(List<RoomSearchField> fieldSet, List<RoomSearchFieldRelation> fieldRelations, List<String> fieldValues, String searchToken, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			IntPtr nFieldSet = IntPtr.Zero;

			IntPtr nFieldRelations = IntPtr.Zero;

			IntPtr nFieldValues = IntPtr.Zero;

			Boolean ret = VidyoUserAdvancedSearchRoomsNative(objPtr, nFieldSet, nFieldRelations, nFieldValues, searchToken, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean AdvancedSearchUsers(List<UserSearchField> fieldSet, List<String> fieldValues, String searchToken, uint index, uint pageSize, IAdvancedSearchUsers _iIAdvancedSearchUsers){
			_mIAdvancedSearchUsers = _iIAdvancedSearchUsers;
			_mOnUserSearchResults = OnUserSearchResultsDelegate;

			IntPtr nFieldSet = IntPtr.Zero;

			IntPtr nFieldValues = IntPtr.Zero;

			Boolean ret = VidyoUserAdvancedSearchUsersNative(objPtr, nFieldSet, nFieldValues, searchToken, index, pageSize, _mOnUserSearchResults);

			return ret;
		}
		public Boolean AllowSubscriber(String userId){

			Boolean ret = VidyoUserAllowSubscriberNative(objPtr, userId);

			return ret;
		}
		public Boolean BlockSubscriber(String userId){

			Boolean ret = VidyoUserBlockSubscriberNative(objPtr, userId);

			return ret;
		}
		public Boolean CreateCall(String userId, String createToken, ICreateCall _iICreateCall){
			_mICreateCall = _iICreateCall;
			_mOnCallCreated = OnCallCreatedDelegate;

			Boolean ret = VidyoUserCreateCallNative(objPtr, userId, createToken, _mOnCallCreated);

			return ret;
		}
		public Boolean CreateRoomFromId(String id, String createToken, ICreateRoomFromId _iICreateRoomFromId){
			_mICreateRoomFromId = _iICreateRoomFromId;
			_mOnRoomCreated = OnRoomCreatedDelegate;

			Boolean ret = VidyoUserCreateRoomFromIdNative(objPtr, id, createToken, _mOnRoomCreated);

			return ret;
		}
		public Boolean CreateRoomWithId(String id, String createToken, ICreateRoomFromId _iICreateRoomFromId){
			_mICreateRoomFromId = _iICreateRoomFromId;
			_mOnRoomCreated = OnRoomCreatedDelegate;

			Boolean ret = VidyoUserCreateRoomWithIdNative(objPtr, id, createToken, _mOnRoomCreated);

			return ret;
		}
		public Boolean CreateTopicRoom(String name, String description, String createToken, ICreateRoomFromId _iICreateRoomFromId){
			_mICreateRoomFromId = _iICreateRoomFromId;
			_mOnRoomCreated = OnRoomCreatedDelegate;

			Boolean ret = VidyoUserCreateTopicRoomNative(objPtr, name, description, createToken, _mOnRoomCreated);

			return ret;
		}
		public Boolean GetContact(String userId, IGetContact _iIGetContact){
			_mIGetContact = _iIGetContact;
			_mOnGetContactResult = OnGetContactResultDelegate;

			Boolean ret = VidyoUserGetContactNative(objPtr, userId, _mOnGetContactResult);

			return ret;
		}
		public Boolean GetConversationRoom(List<String> userIds, String createToken, ICreateRoomFromId _iICreateRoomFromId){
			_mICreateRoomFromId = _iICreateRoomFromId;
			_mOnRoomCreated = OnRoomCreatedDelegate;

			IntPtr nUserIds = IntPtr.Zero;

			Boolean ret = VidyoUserGetConversationRoomNative(objPtr, nUserIds, createToken, _mOnRoomCreated);

			return ret;
		}
		public Boolean GetCurrentRoster(List<Contact> roster){

			IntPtr nRoster = IntPtr.Zero;

			Boolean ret = VidyoUserGetCurrentRosterNative(objPtr, nRoster);

			return ret;
		}
		public Endpoint GetEndpoint(){

			IntPtr ret = VidyoUserGetEndpointNative(objPtr);
			Endpoint csRet = null;
			if(ret != IntPtr.Zero){
				if(Endpoint.VidyoEndpointGetUserDataNative(ret) == IntPtr.Zero)
					csRet = new Endpoint(ret);
				else{
					GCHandle objHandle = (GCHandle)Endpoint.VidyoEndpointGetUserDataNative(ret);
					csRet = (Endpoint)objHandle.Target;
				}
			}

			return csRet;
		}
		public Boolean GetFavoriteRooms(uint index, uint pageSize, IGetFavoriteRooms _iIGetFavoriteRooms){
			_mIGetFavoriteRooms = _iIGetFavoriteRooms;
			_mOnFavoriteRoomResults = OnFavoriteRoomResultsDelegate;

			Boolean ret = VidyoUserGetFavoriteRoomsNative(objPtr, index, pageSize, _mOnFavoriteRoomResults);

			return ret;
		}
		public String GetId(){

			IntPtr ret = VidyoUserGetIdNative(objPtr);

			return Marshal.PtrToStringAnsi(ret);
		}
		public Boolean GetRecentRooms(uint index, uint pageSize, IGetRecentRooms _iIGetRecentRooms){
			_mIGetRecentRooms = _iIGetRecentRooms;
			_mOnRecentRoomResults = OnRecentRoomResultsDelegate;

			Boolean ret = VidyoUserGetRecentRoomsNative(objPtr, index, pageSize, _mOnRecentRoomResults);

			return ret;
		}
		public Boolean GetStats(UserStats stats){

			Boolean ret = VidyoUserGetStatsNative(objPtr, (stats != null) ? stats.GetObjectPtr():IntPtr.Zero);

			return ret;
		}
		public Boolean Login(String username, String password, String host, uint port, String serviceType, ILogin _iILogin){
			_mILogin = _iILogin;
			_mOnLoginComplete = OnLoginCompleteDelegate;
			_mOnLoggedOut = OnLoggedOutDelegate;
			_mOnConnectionStatusChanged = OnConnectionStatusChangedDelegate;
			_mOnTokenReceived = OnTokenReceivedDelegate;
			_mOnWebProxyCredentialsRequest = OnWebProxyCredentialsRequestDelegate;

			Boolean ret = VidyoUserLoginNative(objPtr, username, password, host, port, serviceType, _mOnLoginComplete, _mOnLoggedOut, _mOnConnectionStatusChanged, _mOnTokenReceived, _mOnWebProxyCredentialsRequest);

			return ret;
		}
		public Boolean LoginAsGuest(String displayName, String host, uint port, String serviceType, ILogin _iILogin){
			_mILogin = _iILogin;
			_mOnLoginComplete = OnLoginCompleteDelegate;
			_mOnLoggedOut = OnLoggedOutDelegate;
			_mOnConnectionStatusChanged = OnConnectionStatusChangedDelegate;
			_mOnTokenReceived = OnTokenReceivedDelegate;
			_mOnWebProxyCredentialsRequest = OnWebProxyCredentialsRequestDelegate;

			Boolean ret = VidyoUserLoginAsGuestNative(objPtr, displayName, host, port, serviceType, _mOnLoginComplete, _mOnLoggedOut, _mOnConnectionStatusChanged, _mOnTokenReceived, _mOnWebProxyCredentialsRequest);

			return ret;
		}
		public Boolean LoginWithAccessToken(String accessToken, String host, uint port, String serviceType, ILogin _iILogin){
			_mILogin = _iILogin;
			_mOnLoginComplete = OnLoginCompleteDelegate;
			_mOnLoggedOut = OnLoggedOutDelegate;
			_mOnConnectionStatusChanged = OnConnectionStatusChangedDelegate;
			_mOnTokenReceived = OnTokenReceivedDelegate;
			_mOnWebProxyCredentialsRequest = OnWebProxyCredentialsRequestDelegate;

			Boolean ret = VidyoUserLoginWithAccessTokenNative(objPtr, accessToken, host, port, serviceType, _mOnLoginComplete, _mOnLoggedOut, _mOnConnectionStatusChanged, _mOnTokenReceived, _mOnWebProxyCredentialsRequest);

			return ret;
		}
		public Boolean LoginWithRefreshToken(String refreshToken, String host, uint port, String serviceType, ILogin _iILogin){
			_mILogin = _iILogin;
			_mOnLoginComplete = OnLoginCompleteDelegate;
			_mOnLoggedOut = OnLoggedOutDelegate;
			_mOnConnectionStatusChanged = OnConnectionStatusChangedDelegate;
			_mOnTokenReceived = OnTokenReceivedDelegate;
			_mOnWebProxyCredentialsRequest = OnWebProxyCredentialsRequestDelegate;

			Boolean ret = VidyoUserLoginWithRefreshTokenNative(objPtr, refreshToken, host, port, serviceType, _mOnLoginComplete, _mOnLoggedOut, _mOnConnectionStatusChanged, _mOnTokenReceived, _mOnWebProxyCredentialsRequest);

			return ret;
		}
		public Boolean LoginWithTenantToken(String provisionToken, String host, uint port, String serviceType, ILogin _iILogin){
			_mILogin = _iILogin;
			_mOnLoginComplete = OnLoginCompleteDelegate;
			_mOnLoggedOut = OnLoggedOutDelegate;
			_mOnConnectionStatusChanged = OnConnectionStatusChangedDelegate;
			_mOnTokenReceived = OnTokenReceivedDelegate;
			_mOnWebProxyCredentialsRequest = OnWebProxyCredentialsRequestDelegate;

			Boolean ret = VidyoUserLoginWithTenantTokenNative(objPtr, provisionToken, host, port, serviceType, _mOnLoginComplete, _mOnLoggedOut, _mOnConnectionStatusChanged, _mOnTokenReceived, _mOnWebProxyCredentialsRequest);

			return ret;
		}
		public Boolean Logout(){

			Boolean ret = VidyoUserLogoutNative(objPtr);

			return ret;
		}
		public Boolean RegisterCallEventListener(IRegisterCallEventListener _iIRegisterCallEventListener){
			_mIRegisterCallEventListener = _iIRegisterCallEventListener;
			_mOnCallCreatedByInvite = OnCallCreatedByInviteDelegate;

			Boolean ret = VidyoUserRegisterCallEventListenerNative(objPtr, _mOnCallCreatedByInvite);

			return ret;
		}
		public Boolean RegisterContactEventListener(IRegisterContactEventListener _iIRegisterContactEventListener){
			_mIRegisterContactEventListener = _iIRegisterContactEventListener;
			_mOnUpdateSelf = OnUpdateSelfDelegate;
			_mOnUpdateRosterContact = OnUpdateRosterContactDelegate;
			_mOnRemoveRosterContact = OnRemoveRosterContactDelegate;

			Boolean ret = VidyoUserRegisterContactEventListenerNative(objPtr, _mOnUpdateSelf, _mOnUpdateRosterContact, _mOnRemoveRosterContact);

			return ret;
		}
		public Boolean RegisterLicenseEventListener(IRegisterLicenseEventListener _iIRegisterLicenseEventListener){
			_mIRegisterLicenseEventListener = _iIRegisterLicenseEventListener;
			_mOnLicenseReceived = OnLicenseReceivedDelegate;
			_mOnGetLicenseKey = OnGetLicenseKeyDelegate;

			Boolean ret = VidyoUserRegisterLicenseEventListenerNative(objPtr, _mOnLicenseReceived, _mOnGetLicenseKey);

			return ret;
		}
		public Boolean RegisterRoomEventListener(IRegisterRoomEventListener _iIRegisterRoomEventListener){
			_mIRegisterRoomEventListener = _iIRegisterRoomEventListener;
			_mOnRoomCreatedByInvite = OnRoomCreatedByInviteDelegate;

			Boolean ret = VidyoUserRegisterRoomEventListenerNative(objPtr, _mOnRoomCreatedByInvite);

			return ret;
		}
		public Boolean RemoveRosterContact(String userId){

			Boolean ret = VidyoUserRemoveRosterContactNative(objPtr, userId);

			return ret;
		}
		public Boolean SearchConversationRooms(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchConversationRoomsNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchRooms(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchRoomsNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchRoomsWithName(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchRoomsWithNameNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchRoomsWithOwner(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchRoomsWithOwnerNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchRoomsWithSubject(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchRoomsWithSubjectNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchTopicRooms(String searchText, uint index, uint pageSize, IAdvancedSearchRooms _iIAdvancedSearchRooms){
			_mIAdvancedSearchRooms = _iIAdvancedSearchRooms;
			_mOnRoomSearchResults = OnRoomSearchResultsDelegate;

			Boolean ret = VidyoUserSearchTopicRoomsNative(objPtr, searchText, index, pageSize, _mOnRoomSearchResults);

			return ret;
		}
		public Boolean SearchUsers(String searchText, uint index, uint pageSize, IAdvancedSearchUsers _iIAdvancedSearchUsers){
			_mIAdvancedSearchUsers = _iIAdvancedSearchUsers;
			_mOnUserSearchResults = OnUserSearchResultsDelegate;

			Boolean ret = VidyoUserSearchUsersNative(objPtr, searchText, index, pageSize, _mOnUserSearchResults);

			return ret;
		}
		public void SetCA(String ca, String caFilePath, String caDir){

			VidyoUserSetCANative(objPtr, ca, caFilePath, caDir);
		}
		public void SetDisplayName(String displayName){

			VidyoUserSetDisplayNameNative(objPtr, displayName);
		}
		public void SetWebProxyAddressCredentials(String proxyAddress, String username, String password){

			VidyoUserSetWebProxyAddressCredentialsNative(objPtr, proxyAddress, username, password);
		}
		public Boolean UnregisterCallEventListener(){

			Boolean ret = VidyoUserUnregisterCallEventListenerNative(objPtr);

			return ret;
		}
		public Boolean UnregisterContactEventListener(){

			Boolean ret = VidyoUserUnregisterContactEventListenerNative(objPtr);

			return ret;
		}
		public Boolean UnregisterLicenseEventListener(){

			Boolean ret = VidyoUserUnregisterLicenseEventListenerNative(objPtr);

			return ret;
		}
		public Boolean UnregisterRoomEventListener(){

			Boolean ret = VidyoUserUnregisterRoomEventListenerNative(objPtr);

			return ret;
		}
		public Boolean UpdatePresence(Contact.ContactPresenceState state, String status){

			Boolean ret = VidyoUserUpdatePresenceNative(objPtr, state, status);

			return ret;
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnCallCreated))]
#endif
		private static void OnCallCreatedDelegate(IntPtr u, IntPtr call, UserCallCreateResult result, IntPtr createToken){
			Call csCall = null;
			if(call != IntPtr.Zero){
				if(Call.VidyoCallGetUserDataNative(call) == IntPtr.Zero)
					csCall = new Call(call);
				else{
					GCHandle objHandle = (GCHandle)Call.VidyoCallGetUserDataNative(call);
					csCall = (Call)objHandle.Target;
				}
			}
			if(_mICreateCall != null)
				_mICreateCall.OnCallCreated(csCall, result, Marshal.PtrToStringAnsi(createToken));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnCallCreatedByInvite))]
#endif
		private static void OnCallCreatedByInviteDelegate(IntPtr u, IntPtr call, IntPtr inviter){
			Call csCall = null;
			if(call != IntPtr.Zero){
				if(Call.VidyoCallGetUserDataNative(call) == IntPtr.Zero)
					csCall = new Call(call);
				else{
					GCHandle objHandle = (GCHandle)Call.VidyoCallGetUserDataNative(call);
					csCall = (Call)objHandle.Target;
				}
			}
			Contact csInviter = new Contact(inviter);
			if(_mIRegisterCallEventListener != null)
				_mIRegisterCallEventListener.OnCallCreatedByInvite(csCall, csInviter);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnConnectionStatusChanged))]
#endif
		private static void OnConnectionStatusChangedDelegate(IntPtr u, UserConnectionStatusChangedReason reason){
			if(_mILogin != null)
				_mILogin.OnConnectionStatusChanged(reason);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnFavoriteRoomResults))]
#endif
		private static void OnFavoriteRoomResultsDelegate(IntPtr u, UserSearchResult searchResult, IntPtr roomInfo){
			List<RoomInfo> csRoomInfo = new List<RoomInfo>();
			int nRoomInfoSize = 0;
			IntPtr nRoomInfo = VidyoUserOnFavoriteRoomResultsGetroomInfoArrayNative(roomInfo, ref nRoomInfoSize);
			int nRoomInfoIndex = 0;
			while (nRoomInfoIndex < nRoomInfoSize) {
				RoomInfo csTroomInfo = new RoomInfo(Marshal.ReadIntPtr(nRoomInfo + (nRoomInfoIndex * Marshal.SizeOf(nRoomInfo))));
				csRoomInfo.Add(csTroomInfo);
				nRoomInfoIndex++;
			}

			if(_mIGetFavoriteRooms != null)
				_mIGetFavoriteRooms.OnFavoriteRoomResults(searchResult, csRoomInfo);
			VidyoUserOnFavoriteRoomResultsFreeroomInfoArrayNative(nRoomInfo, nRoomInfoSize);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnGetContactResult))]
#endif
		private static void OnGetContactResultDelegate(IntPtr u, IntPtr contact, UserGetContactResult result){
			Contact csContact = new Contact(contact);
			if(_mIGetContact != null)
				_mIGetContact.OnGetContactResult(csContact, result);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnGetLicenseKey))]
#endif
		private static void OnGetLicenseKeyDelegate(IntPtr u, IntPtr licenseKey){
			if(_mIRegisterLicenseEventListener != null)
				_mIRegisterLicenseEventListener.OnGetLicenseKey(Marshal.PtrToStringAnsi(licenseKey));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnLicenseReceived))]
#endif
		private static void OnLicenseReceivedDelegate(IntPtr u, IntPtr licenseKey){
			if(_mIRegisterLicenseEventListener != null)
				_mIRegisterLicenseEventListener.OnLicenseReceived(Marshal.PtrToStringAnsi(licenseKey));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnLoggedOut))]
#endif
		private static void OnLoggedOutDelegate(IntPtr u, UserLogoutReason reason){
			if(_mILogin != null)
				_mILogin.OnLoggedOut(reason);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnLoginComplete))]
#endif
		private static void OnLoginCompleteDelegate(IntPtr u, UserLoginResult result, Boolean secure){
			if(_mILogin != null)
				_mILogin.OnLoginComplete(result, secure);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRecentRoomResults))]
#endif
		private static void OnRecentRoomResultsDelegate(IntPtr u, UserSearchResult searchResult, IntPtr roomInfo){
			List<RoomInfo> csRoomInfo = new List<RoomInfo>();
			int nRoomInfoSize = 0;
			IntPtr nRoomInfo = VidyoUserOnRecentRoomResultsGetroomInfoArrayNative(roomInfo, ref nRoomInfoSize);
			int nRoomInfoIndex = 0;
			while (nRoomInfoIndex < nRoomInfoSize) {
				RoomInfo csTroomInfo = new RoomInfo(Marshal.ReadIntPtr(nRoomInfo + (nRoomInfoIndex * Marshal.SizeOf(nRoomInfo))));
				csRoomInfo.Add(csTroomInfo);
				nRoomInfoIndex++;
			}

			if(_mIGetRecentRooms != null)
				_mIGetRecentRooms.OnRecentRoomResults(searchResult, csRoomInfo);
			VidyoUserOnRecentRoomResultsFreeroomInfoArrayNative(nRoomInfo, nRoomInfoSize);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRemoveRosterContact))]
#endif
		private static void OnRemoveRosterContactDelegate(IntPtr u, IntPtr uri){
			if(_mIRegisterContactEventListener != null)
				_mIRegisterContactEventListener.OnRemoveRosterContact(Marshal.PtrToStringAnsi(uri));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRoomCreated))]
#endif
		private static void OnRoomCreatedDelegate(IntPtr u, IntPtr room, UserRoomCreateResult result, IntPtr createToken){
			Room csRoom = null;
			if(room != IntPtr.Zero){
				if(Room.VidyoRoomGetUserDataNative(room) == IntPtr.Zero)
					csRoom = new Room(room);
				else{
					GCHandle objHandle = (GCHandle)Room.VidyoRoomGetUserDataNative(room);
					csRoom = (Room)objHandle.Target;
				}
			}
			if(_mICreateRoomFromId != null)
				_mICreateRoomFromId.OnRoomCreated(csRoom, result, Marshal.PtrToStringAnsi(createToken));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRoomCreatedByInvite))]
#endif
		private static void OnRoomCreatedByInviteDelegate(IntPtr u, IntPtr room, IntPtr inviter, IntPtr message){
			Room csRoom = null;
			if(room != IntPtr.Zero){
				if(Room.VidyoRoomGetUserDataNative(room) == IntPtr.Zero)
					csRoom = new Room(room);
				else{
					GCHandle objHandle = (GCHandle)Room.VidyoRoomGetUserDataNative(room);
					csRoom = (Room)objHandle.Target;
				}
			}
			Contact csInviter = new Contact(inviter);
			if(_mIRegisterRoomEventListener != null)
				_mIRegisterRoomEventListener.OnRoomCreatedByInvite(csRoom, csInviter, Marshal.PtrToStringAnsi(message));
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRoomSearchResults))]
#endif
		private static void OnRoomSearchResultsDelegate(IntPtr u, IntPtr searchText, UserSearchResult searchResult, IntPtr roomInfo, ulong numRecords){
			List<RoomInfo> csRoomInfo = new List<RoomInfo>();
			int nRoomInfoSize = 0;
			IntPtr nRoomInfo = VidyoUserOnRoomSearchResultsGetroomInfoArrayNative(roomInfo, ref nRoomInfoSize);
			int nRoomInfoIndex = 0;
			while (nRoomInfoIndex < nRoomInfoSize) {
				RoomInfo csTroomInfo = new RoomInfo(Marshal.ReadIntPtr(nRoomInfo + (nRoomInfoIndex * Marshal.SizeOf(nRoomInfo))));
				csRoomInfo.Add(csTroomInfo);
				nRoomInfoIndex++;
			}

			if(_mIAdvancedSearchRooms != null)
				_mIAdvancedSearchRooms.OnRoomSearchResults(Marshal.PtrToStringAnsi(searchText), searchResult, csRoomInfo, numRecords);
			VidyoUserOnRoomSearchResultsFreeroomInfoArrayNative(nRoomInfo, nRoomInfoSize);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnTokenReceived))]
#endif
		private static void OnTokenReceivedDelegate(IntPtr u, IntPtr token, UserTokenType tokenType){
			if(_mILogin != null)
				_mILogin.OnTokenReceived(Marshal.PtrToStringAnsi(token), tokenType);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnUpdateRosterContact))]
#endif
		private static void OnUpdateRosterContactDelegate(IntPtr u, IntPtr contact){
			Contact csContact = new Contact(contact);
			if(_mIRegisterContactEventListener != null)
				_mIRegisterContactEventListener.OnUpdateRosterContact(csContact);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnUpdateSelf))]
#endif
		private static void OnUpdateSelfDelegate(IntPtr u, IntPtr contact){
			Contact csContact = new Contact(contact);
			if(_mIRegisterContactEventListener != null)
				_mIRegisterContactEventListener.OnUpdateSelf(csContact);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnUserSearchResults))]
#endif
		private static void OnUserSearchResultsDelegate(IntPtr u, IntPtr searchText, UserSearchResult searchResult, IntPtr contacts, ulong numRecords){
			List<ContactInfo> csContacts = new List<ContactInfo>();
			int nContactsSize = 0;
			IntPtr nContacts = VidyoUserOnUserSearchResultsGetcontactsArrayNative(contacts, ref nContactsSize);
			int nContactsIndex = 0;
			while (nContactsIndex < nContactsSize) {
				ContactInfo csTcontacts = new ContactInfo(Marshal.ReadIntPtr(nContacts + (nContactsIndex * Marshal.SizeOf(nContacts))));
				csContacts.Add(csTcontacts);
				nContactsIndex++;
			}

			if(_mIAdvancedSearchUsers != null)
				_mIAdvancedSearchUsers.OnUserSearchResults(Marshal.PtrToStringAnsi(searchText), searchResult, csContacts, numRecords);
			VidyoUserOnUserSearchResultsFreecontactsArrayNative(nContacts, nContactsSize);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnWebProxyCredentialsRequest))]
#endif
		private static void OnWebProxyCredentialsRequestDelegate(IntPtr u){
			if(_mILogin != null)
				_mILogin.OnWebProxyCredentialsRequest();
		}
	};
}
